sudo: required
services: 
  - docker

before_install:
  - docker build -t js/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true js/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-913524929098"
  bucket_path: "frontend"
  on:
    branch: master
    access_key_id: $Access_key_ID
    secret_access_key: $AWS_secret_key